### PR TITLE
Show bad statuses for collections over threshold

### PR DESCRIPTION
**Pull request by leplatrem**
screenshot from 2019-02-13 15-37-01

### CODE REVIEW

**Comment by peterbe** [comment]
So it just repeats the bad ones one more time? Perhaps better would be a `click` option to hide non-error ones.

**Comment by peterbe** [comment]
By the way, you can put the REDASH_API_KEY in a `.env` file, did you see that?

**Comment by leplatrem** [comment]
> So it just repeats the bad ones one more time? Perhaps better would be a `click` option to hide non-error ones.

Well, it gives the distribution of errors, which is an important information IMO

**Comment by leplatrem** [comment]
> By the way, you can put the REDASH_API_KEY in a `.env` file, did you see that?

I hadn't paid attention, thanks!

**Pull request merged**
